# Generated by Django 5.0.4 on 2024-04-25 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmployerADD",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_name", models.CharField(max_length=40)),
                ("description", models.TextField(max_length=500)),
                ("foreign_citizens", models.BooleanField()),
                ("sector", models.CharField(max_length=40)),
                ("remote_status", models.BooleanField()),
                (
                    "city",
                    models.CharField(
                        choices=[
                            ("YV", "Yerevan"),
                            ("ARM", "Armavir"),
                            ("AR", "Ararat"),
                            ("ART", "Ararat"),
                            ("KT", "Kotayk"),
                            ("SHI", "Shirak"),
                            ("LR", "Lorri"),
                            ("GK", "Geharkunik"),
                            ("SY", "Syunik"),
                            ("ARG", "Aragatsotn"),
                            ("TV", "Tavush"),
                            ("VD", "Vayoc Dzor"),
                            ("IT", "International"),
                        ],
                        max_length=30,
                    ),
                ),
                ("job_time", models.CharField(max_length=30)),
                ("experience", models.CharField(max_length=40)),
                ("working_schedule", models.CharField(max_length=40)),
                ("salary_start", models.CharField(max_length=40)),
                ("salary_end", models.CharField(max_length=40)),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("Armenian dram", "AMD"),
                            ("United States Dollars", "USD"),
                        ],
                        max_length=25,
                    ),
                ),
                ("frequency", models.CharField(max_length=20)),
                ("application_deadline", models.CharField(max_length=40)),
                ("application_procedure", models.CharField(max_length=40)),
                ("status", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="EmployerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_add_id", models.BigIntegerField(auto_created=True)),
                ("company_name", models.CharField(max_length=50, unique=True)),
                ("avatar", models.ImageField(upload_to="media/employer/avatar")),
                ("name_surname", models.CharField(max_length=40)),
                ("phone_number", models.CharField(max_length=20, unique=True)),
                ("status", models.BooleanField()),
            ],
        ),
    ]
