# Generated by Django 5.0.4 on 2024-04-14 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Apartment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=30)),
                ("price", models.PositiveIntegerField()),
                ("currency", models.CharField(max_length=5)),
                ("optional_description", models.TextField(max_length=500)),
                ("total_area", models.PositiveIntegerField()),
                ("rooms_count", models.PositiveIntegerField()),
                ("bathrooms_count", models.PositiveIntegerField()),
                ("ceiling_height", models.PositiveIntegerField()),
                ("apartment_floor", models.PositiveIntegerField()),
                ("apartment_repair", models.CharField(max_length=35)),
            ],
        ),
    ]
