# Generated by Django 5.0.4 on 2024-04-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("realestate", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrivateHouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=30)),
                ("house_type", models.CharField(max_length=30)),
                ("price", models.PositiveIntegerField()),
                ("currency", models.CharField(max_length=5)),
                ("building_type", models.CharField(max_length=20)),
                ("house_area", models.PositiveIntegerField()),
                ("floor_count", models.PositiveIntegerField()),
                ("rooms_count", models.PositiveIntegerField()),
                ("bathrooms_count", models.PositiveIntegerField()),
                ("furniture", models.CharField(max_length=20)),
                ("garage", models.CharField(max_length=15)),
                ("apartment_repair", models.CharField(max_length=35)),
                ("total_area", models.PositiveIntegerField()),
                ("status", models.CharField(max_length=15)),
            ],
        ),
    ]
