# Generated by Django 5.0.4 on 2024-04-14 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("realestate", "0002_privatehouse"),
    ]

    operations = [
        migrations.AddField(
            model_name="apartment",
            name="house_type",
            field=models.CharField(default=5, max_length=30),
            preserve_default=False,
        ),
    ]
