# Generated by Django 5.0.4 on 2024-04-14 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("realestate", "0003_apartment_house_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="apartment",
            name="furniture",
            field=models.CharField(default=12, max_length=20),
            preserve_default=False,
        ),
    ]
