# Generated by Django 5.0.4 on 2024-04-15 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("realestate", "0004_apartment_furniture"),
    ]

    operations = [
        migrations.CreateModel(
            name="GaragesAndParking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=20)),
                ("type", models.CharField(max_length=20)),
                ("price", models.PositiveIntegerField()),
                ("floor_area", models.PositiveIntegerField()),
                ("amenities", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Land",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=30)),
                ("type", models.CharField(max_length=20)),
                ("price", models.PositiveIntegerField()),
                ("currency", models.CharField(max_length=5)),
                ("land_area", models.PositiveIntegerField()),
                ("service_lines", models.CharField(max_length=20)),
            ],
        ),
    ]
