# Generated by Django 5.0.4 on 2024-04-18 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("realestate", "0005_garagesandparking_land"),
    ]

    operations = [
        migrations.CreateModel(
            name="LongTermApartmentRentals",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("private", models.BooleanField(default=False)),
                ("agency", models.BooleanField(default=False)),
                ("verified_ads", models.BooleanField(default=False)),
                ("price", models.PositiveIntegerField()),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("Armenian dram", "AMD"),
                            ("United States Dollars", "USD"),
                        ],
                        max_length=21,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("YV", "Yerevan"),
                            ("ARM", "Armavir"),
                            ("AR", "Ararat"),
                            ("ART", "Ararat"),
                            ("KT", "Kotayk"),
                            ("SHI", "Shirak"),
                            ("LR", "Lorri"),
                            ("GK", "Geharkunik"),
                            ("SY", "Syunik"),
                            ("ARG", "Aragatsotn"),
                            ("TV", "Tavush"),
                            ("VD", "Vayoc Dzor"),
                            ("IT", "International"),
                        ],
                        max_length=15,
                        null=True,
                    ),
                ),
                ("street", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "house_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("hide_house_number_in_ad", models.BooleanField(default=False)),
                (
                    "construction_type",
                    models.CharField(
                        choices=[
                            ("Stone", "Stone"),
                            ("Panels", "Panels"),
                            ("Monolith", "Monolith"),
                            ("Bricks", "Bricks"),
                            ("Cassette", "Cassette"),
                            ("Wooden", "Wooden"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "new_construction",
                    models.CharField(
                        choices=[("No", "No"), ("Yes", "Yes")], max_length=10
                    ),
                ),
                (
                    "elevator",
                    models.CharField(
                        choices=[
                            ("Available", "Available"),
                            ("Unavailable", "Unavailable"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "floors_in_building",
                    models.CharField(
                        choices=[("1", "1"), ("2", "2"), ("3", "3"), ("4+", "4+")],
                        max_length=10,
                    ),
                ),
                (
                    "the_house_has",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Intercom entry", "Intercom entry"),
                            ("Concierge", "Concierge"),
                            ("Playground", "Playground"),
                        ],
                        max_length=25,
                        null=True,
                    ),
                ),
                (
                    "parking",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Outdoor parking", "Outdoor parking"),
                            ("Covered parking", "Covered parking"),
                            ("Garage", "Garage"),
                        ],
                        max_length=25,
                        null=True,
                    ),
                ),
                ("floor_area", models.PositiveSmallIntegerField()),
                (
                    "number_of_rooms",
                    models.CharField(
                        choices=[
                            ("1", "1"),
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                            ("5", "5"),
                            ("6", "6"),
                            ("7", "7"),
                            ("8+", "8+"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "number_of_bathrooms",
                    models.CharField(
                        choices=[("1", "1"), ("2", "2"), ("3+", "3+")], max_length=10
                    ),
                ),
                (
                    "ceiling_height",
                    models.CharField(
                        choices=[
                            ("2.5", "from 2.5 m"),
                            ("2.6", "from 2.6 m"),
                            ("2.7", "from 2.7 m"),
                            ("2.75", "from 2.75 m"),
                            ("2.8", "from 2.8 m"),
                            ("3", "from 3 m"),
                            ("3.2", "from 3.2 m"),
                            ("3.5", "from 3.5 m"),
                        ],
                        max_length=20,
                    ),
                ),
                ("apartment_floor", models.PositiveIntegerField()),
                (
                    "balcony",
                    models.CharField(
                        choices=[
                            ("Not available", "Not available"),
                            ("Open balcony", "Open balcony"),
                            ("Closed balcony", "Closed balcony"),
                            ("Multiple balconies", "Multiple balconies"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "furniture",
                    models.CharField(
                        choices=[
                            ("Available", "Available"),
                            ("Not available", "Not available"),
                            ("Partial furniture", "Partial furniture"),
                            ("By agreement", "By agreement"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "renovation",
                    models.CharField(
                        choices=[
                            ("No Renovation", "No Renovation"),
                            ("Old Renovation", "Old Renovation"),
                            ("Partial Renovation", "Partial Renovation"),
                            ("Cosmetic Renovation", "Cosmetic Renovation"),
                            ("Euro Renovation", "Euro Renovation"),
                            ("Designer Renovation", "Designer Renovation"),
                            ("Major Renovation", "Major Renovation"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "amenities",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Television", "Television"),
                            ("Air Conditioner", "Air Conditioner"),
                            ("Internet", "Internet"),
                            ("Parking space", "Parking space"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "appliances",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Fridge", "Fridge"),
                            ("Stove", "Stove"),
                            ("Microwave", "Microwave"),
                            ("Coffee maker", "Coffee maker"),
                            ("Dishwasher", "Dishwasher"),
                            ("Washing machine", "Washing machine"),
                            ("Drying machine", "Drying machine"),
                            ("Water heater", "Water heater"),
                            ("Iron", "Iron"),
                            ("Hair dryer", "Hair dryer"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "window_views",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Yard view", "Yard view"),
                            ("Street view", "Street view"),
                            ("City view", "City view"),
                            ("Park view", "Park view"),
                            ("View of Ararat", "View of Ararat"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "children_are_welcome",
                    models.CharField(
                        choices=[
                            ("Yes", "Yes"),
                            ("No", "No"),
                            ("Negotiable", "Negotiable"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "pets_allowed",
                    models.CharField(
                        choices=[
                            ("Yes", "Yes"),
                            ("No", "No"),
                            ("Negotiable", "Negotiable"),
                        ],
                        max_length=20,
                    ),
                ),
                ("optional_description", models.TextField(max_length=1000)),
                ("photos", models.ImageField(upload_to="media/product/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("available", models.BooleanField(default=True)),
                ("apartment_number", models.PositiveSmallIntegerField()),
                ("cadastral_number", models.PositiveSmallIntegerField()),
                (
                    "supporting_document",
                    models.ImageField(upload_to="media/documents/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LongTermRentalsCommercialProperties",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("private", models.BooleanField(default=False)),
                ("agency", models.BooleanField(default=False)),
                ("verified_ads", models.BooleanField(default=False)),
                ("price", models.PositiveIntegerField()),
                ("currency", models.CharField(max_length=5)),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("YV", "Yerevan"),
                            ("ARM", "Armavir"),
                            ("AR", "Ararat"),
                            ("ART", "Ararat"),
                            ("KT", "Kotayk"),
                            ("SHI", "Shirak"),
                            ("LR", "Lorri"),
                            ("GK", "Geharkunik"),
                            ("SY", "Syunik"),
                            ("ARG", "Aragatsotn"),
                            ("TV", "Tavush"),
                            ("VD", "Vayoc Dzor"),
                            ("IT", "International"),
                        ],
                        max_length=15,
                        null=True,
                    ),
                ),
                ("street", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "house_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "info_type",
                    models.CharField(
                        choices=[
                            ("Office space", "Office space"),
                            ("Retail space", "Retail space"),
                            (
                                "Industrial and manufacturing",
                                "Industrial and manufacturing",
                            ),
                            ("Warehouse", "Warehouse"),
                            ("Restaurant", "Restaurant"),
                            ("Automotive service", "Automotive service"),
                            ("Functioning business", "Functioning business"),
                            ("Building", "Building"),
                            ("Hotel", "Hotel"),
                            ("Multifunctional space", "Multifunctional space"),
                            ("Agricultural space", "Agricultural space"),
                            ("Everything else", "Everything else"),
                        ],
                        max_length=50,
                    ),
                ),
                ("floor_area", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "furniture",
                    models.CharField(
                        choices=[
                            ("Available", "Available"),
                            ("Not available", "Not available"),
                            ("Partial furniture", "Partial furniture"),
                            ("By agreement", "By agreement"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "elevator",
                    models.CharField(
                        choices=[
                            ("Available", "Available"),
                            ("Unavailable", "Unavailable"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "location_from_the_street",
                    models.CharField(
                        choices=[
                            ("First line", "First line"),
                            ("Second line", "Second line"),
                            ("Other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "entrance",
                    models.CharField(
                        choices=[
                            ("Common from the Street", "Common from the Street"),
                            ("Common from the Courtyard", "Common from the Courtyard"),
                            ("Separate from Street", "Separate from Street"),
                            ("Separate from Courtyard", "Separate from Courtyards"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "parking",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Outdoor parking", "Outdoor parking"),
                            ("Covered parking", "Covered parking"),
                            ("Garage", "Garage"),
                        ],
                        max_length=25,
                        null=True,
                    ),
                ),
                (
                    "lease_type",
                    models.CharField(
                        choices=[
                            ("Direct Lease", "Direct Lease"),
                            ("Sublease", "Sublease"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "minimum_rental_period",
                    models.CharField(
                        choices=[
                            ("1 month", "1 month"),
                            ("2 month", "2 month"),
                            ("3 month", "3 month"),
                            ("4 month", "4 month"),
                            ("6 month", "6 month"),
                            ("9 month", "9 month"),
                            ("1 year", "1 year"),
                            ("2 years", "2 years"),
                            ("3 years", "3 years"),
                            ("5 years", "5 years"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "prepayment",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Without prepayment", "Without prepayment"),
                            ("By agreement", "By agreement"),
                            ("2 weeks", "2 weeks"),
                            ("1 month", "1 month"),
                            ("6 weeks", "6 weeks"),
                            ("2 month", "2 month"),
                            ("3 month", "3 month"),
                            ("4 month", "4 month"),
                            ("6 month", "6 month"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "utility_payments",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Included", "Included"),
                            ("Not included", "Not included"),
                            ("By agreement", "By agreement"),
                        ],
                        max_length=50,
                    ),
                ),
                ("optional_description", models.TextField(max_length=1000)),
                ("photos", models.ImageField(upload_to="media/product")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("available", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="LongTermRentalsHouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("private", models.BooleanField(default=False)),
                ("agency", models.BooleanField(default=False)),
                ("verified_ads", models.BooleanField(default=False)),
                ("price", models.PositiveIntegerField()),
                ("currency", models.CharField(max_length=5)),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("YV", "Yerevan"),
                            ("ARM", "Armavir"),
                            ("AR", "Ararat"),
                            ("ART", "Ararat"),
                            ("KT", "Kotayk"),
                            ("SHI", "Shirak"),
                            ("LR", "Lorri"),
                            ("GK", "Geharkunik"),
                            ("SY", "Syunik"),
                            ("ARG", "Aragatsotn"),
                            ("TV", "Tavush"),
                            ("VD", "Vayoc Dzor"),
                            ("IT", "International"),
                        ],
                        max_length=15,
                        null=True,
                    ),
                ),
                ("street", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "house_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("hide_house_number_in_ad", models.BooleanField(default=False)),
                (
                    "construction_type",
                    models.CharField(
                        choices=[
                            ("Stone", "Stone"),
                            ("Panels", "Panels"),
                            ("Monolith", "Monolith"),
                            ("Bricks", "Bricks"),
                            ("Cassette", "Cassette"),
                            ("Wooden", "Wooden"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "new_construction",
                    models.CharField(
                        choices=[("No", "No"), ("Yes", "Yes")], max_length=10
                    ),
                ),
                ("floor_area", models.PositiveSmallIntegerField()),
                (
                    "floors_in_building",
                    models.CharField(
                        choices=[("1", "1"), ("2", "2"), ("3", "3"), ("4+", "4+")],
                        max_length=10,
                    ),
                ),
                (
                    "number_of_rooms",
                    models.CharField(
                        choices=[
                            ("1", "1"),
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                            ("5", "5"),
                            ("6", "6"),
                            ("7", "7"),
                            ("8+", "8+"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "number_of_bathrooms",
                    models.CharField(
                        choices=[("1", "1"), ("2", "2"), ("3+", "3+")], max_length=10
                    ),
                ),
                (
                    "furniture",
                    models.CharField(
                        choices=[
                            ("Available", "Available"),
                            ("Not available", "Not available"),
                            ("Partial furniture", "Partial furniture"),
                            ("By agreement", "By agreement"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "parking",
                    models.CharField(
                        choices=[
                            ("Outdoor parking", "Outdoor parking"),
                            ("Covered parking", "Covered parking"),
                            ("Garage", "Garage"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "renovation",
                    models.CharField(
                        choices=[
                            ("No Renovation", "No Renovation"),
                            ("Old Renovation", "Old Renovation"),
                            ("Partial Renovation", "Partial Renovation"),
                            ("Cosmetic Renovation", "Cosmetic Renovation"),
                            ("Euro Renovation", "Euro Renovation"),
                            ("Designer Renovation", "Designer Renovation"),
                            ("Major Renovation", "Major Renovation"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "amenities",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Television", "Television"),
                            ("Air Conditioner", "Air Conditioner"),
                            ("Internet", "Internet"),
                            ("Parking space", "Parking space"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "appliances",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Fridge", "Fridge"),
                            ("Stove", "Stove"),
                            ("Microwave", "Microwave"),
                            ("Coffee maker", "Coffee maker"),
                            ("Dishwasher", "Dishwasher"),
                            ("Washing machine", "Washing machine"),
                            ("Drying machine", "Drying machine"),
                            ("Water heater", "Water heater"),
                            ("Iron", "Iron"),
                            ("Hair dryer", "Hair dryer"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                ("land_area", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "children_are_welcome",
                    models.CharField(
                        choices=[
                            ("Yes", "Yes"),
                            ("No", "No"),
                            ("Negotiable", "Negotiable"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "pets_allowed",
                    models.CharField(
                        choices=[
                            ("Yes", "Yes"),
                            ("No", "No"),
                            ("Negotiable", "Negotiable"),
                        ],
                        max_length=20,
                    ),
                ),
                ("optional_description", models.TextField(max_length=1000)),
                ("photos", models.ImageField(upload_to="media/product/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("available", models.BooleanField(default=True)),
                ("apartment_number", models.PositiveSmallIntegerField()),
                ("cadastral_number", models.PositiveSmallIntegerField()),
                (
                    "supporting_document",
                    models.ImageField(upload_to="media/documents/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LongTermRentalsLand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("private", models.BooleanField(default=False)),
                ("agency", models.BooleanField(default=False)),
                ("verified_ads", models.BooleanField(default=False)),
                ("price", models.PositiveIntegerField()),
                ("currency", models.CharField(max_length=5)),
                (
                    "prepayment",
                    models.CharField(
                        choices=[
                            ("Without prepayment", "Without prepayment"),
                            ("By agreement", "By agreement"),
                            ("2 weeks", "2 weeks"),
                            ("1 month", "1 month"),
                            ("6 weeks", "6 weeks"),
                            ("2 month", "2 month"),
                            ("3 month", "3 month"),
                            ("4 month", "4 month"),
                            ("6 month", "6 month"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("YV", "Yerevan"),
                            ("ARM", "Armavir"),
                            ("AR", "Ararat"),
                            ("ART", "Ararat"),
                            ("KT", "Kotayk"),
                            ("SHI", "Shirak"),
                            ("LR", "Lorri"),
                            ("GK", "Geharkunik"),
                            ("SY", "Syunik"),
                            ("ARG", "Aragatsotn"),
                            ("TV", "Tavush"),
                            ("VD", "Vayoc Dzor"),
                            ("IT", "International"),
                        ],
                        max_length=15,
                        null=True,
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "info_type",
                    models.CharField(
                        choices=[
                            ("Direct Lease", "Direct Lease"),
                            ("Sublease", "Sublease"),
                        ],
                        max_length=50,
                    ),
                ),
                ("land_area", models.PositiveSmallIntegerField()),
                ("electricity", models.BooleanField(default=False)),
                ("water_supply", models.BooleanField(default=False)),
                ("natural_gas", models.BooleanField(default=False)),
                ("sewerage", models.BooleanField(default=False)),
                ("description", models.TextField(max_length=1000)),
                ("photo", models.ImageField(upload_to="media/product")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("available", models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Apartment",
        ),
        migrations.DeleteModel(
            name="GaragesAndParking",
        ),
        migrations.DeleteModel(
            name="Land",
        ),
        migrations.DeleteModel(
            name="PrivateHouse",
        ),
    ]
