# Generated by Django 5.0.4 on 2024-04-23 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CandidateADD",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=40)),
                ("avatar", models.ImageField(upload_to="media/avatar")),
                ("title", models.CharField(max_length=50)),
                ("sector", models.CharField(max_length=40)),
                ("deadline", models.DateTimeField()),
                (
                    "city",
                    models.CharField(
                        choices=[
                            ("YV", "Yerevan"),
                            ("ARM", "Armavir"),
                            ("AR", "Ararat"),
                            ("ART", "Ararat"),
                            ("KT", "Kotayk"),
                            ("SHI", "Shirak"),
                            ("LR", "Lorri"),
                            ("GK", "Geharkunik"),
                            ("SY", "Syunik"),
                            ("ARG", "Aragatsotn"),
                            ("TV", "Tavush"),
                            ("VD", "Vayoc Dzor"),
                            ("IT", "International"),
                        ],
                        max_length=20,
                    ),
                ),
                ("position", models.CharField(max_length=30)),
                ("salary", models.CharField(max_length=20)),
                ("work_schedule", models.CharField(max_length=40)),
                ("work_experience", models.CharField(max_length=40)),
                ("description", models.TextField(max_length=1000)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="CandidateProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_surname", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=50, unique=True)),
                ("password", models.CharField(max_length=25, unique=True)),
                ("activated_status", models.BooleanField()),
                (
                    "avatar",
                    models.ImageField(blank=True, null=True, upload_to="media/avatar"),
                ),
                ("resume", models.TextField(max_length=1000)),
                (
                    "resume_file",
                    models.FileField(blank=True, null=True, upload_to="media/resume"),
                ),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("YV", "Yerevan"),
                            ("ARM", "Armavir"),
                            ("AR", "Ararat"),
                            ("ART", "Ararat"),
                            ("KT", "Kotayk"),
                            ("SHI", "Shirak"),
                            ("LR", "Lorri"),
                            ("GK", "Geharkunik"),
                            ("SY", "Syunik"),
                            ("ARG", "Aragatsotn"),
                            ("TV", "Tavush"),
                            ("VD", "Vayoc Dzor"),
                            ("IT", "International"),
                        ],
                        max_length=40,
                    ),
                ),
                ("address", models.CharField(max_length=50)),
                ("birth_date", models.DateTimeField()),
                ("telephone_number", models.CharField(max_length=13)),
                ("my_application_id", models.CharField(max_length=25, unique=True)),
            ],
        ),
    ]
