# Generated by Django 5.0.6 on 2024-05-09 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Phone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "model",
                    models.CharField(
                        choices=[
                            ("Iphone X", "Iphone X"),
                            ("Iphone 15 pro", "Iphone 15 pro"),
                            ("Samsung Galaxy A33", "Samsung Galaxy A33"),
                            ("Xiaomi T 13 PRO", "Xiaomi T13 PRO"),
                        ],
                        max_length=30,
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                (
                    "memory",
                    models.CharField(
                        choices=[
                            ("128gb", "128gb"),
                            ("256gb", "256gb"),
                            ("512gb", "512gb"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("Black", "Black"),
                            ("White", "White"),
                            ("Blue", "Blue"),
                            ("Gold", "Gold"),
                        ],
                        max_length=20,
                    ),
                ),
                ("status", models.BooleanField(default=False)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="media/phone"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Owner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("picture", models.ImageField(upload_to="media/owners")),
                (
                    "phone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phones",
                        to="polls.phone",
                    ),
                ),
                (
                    "phone_models",
                    models.ManyToManyField(
                        blank=True, related_name="owners", to="polls.phone"
                    ),
                ),
            ],
        ),
    ]
