# Generated by Django 5.0.6 on 2024-05-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phone",
            name="slug",
            field=models.SlugField(),
        ),
    ]
