# Generated by Django 5.0.4 on 2024-04-14 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=20)),
                ("brand", models.CharField(max_length=20)),
                ("color", models.CharField(help_text="Color of Bike", max_length=20)),
                ("description", models.TextField(help_text="About the Bike")),
                ("year", models.CharField(max_length=5)),
                ("price", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Boat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=20)),
                ("brand", models.CharField(max_length=20)),
                (
                    "comp",
                    models.CharField(
                        default="FULL", help_text="Complectation of Boat", max_length=20
                    ),
                ),
                ("color", models.CharField(help_text="Color of Boat", max_length=20)),
                ("description", models.TextField(help_text="About the Boat")),
                ("year", models.CharField(max_length=5)),
                ("price", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Bus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=25)),
                ("brand", models.CharField(max_length=20)),
                (
                    "comp",
                    models.CharField(
                        default="FULL", help_text="Complectation of Bus", max_length=20
                    ),
                ),
                ("passage", models.CharField(max_length=20)),
                ("color", models.CharField(help_text="Color of Bus", max_length=20)),
                ("description", models.TextField(help_text="About the Truck")),
                ("year", models.CharField(max_length=5)),
                ("price", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=20)),
                ("brand", models.CharField(max_length=20)),
                (
                    "comp",
                    models.CharField(
                        default="FULL", help_text="Complectation of Car", max_length=20
                    ),
                ),
                ("color", models.CharField(help_text="Color of car", max_length=20)),
                ("description", models.TextField(help_text="About the Car")),
                ("year", models.CharField(max_length=5)),
                ("price", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="SpecialTechnic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=20)),
                ("year", models.CharField(max_length=5)),
                ("optional", models.TextField(help_text="About the Technic")),
                ("price", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Truck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=20)),
                ("brand", models.CharField(max_length=20)),
                ("color", models.CharField(max_length=20)),
                ("description", models.TextField(help_text="About the Truck")),
                ("year", models.CharField(max_length=5)),
                ("price", models.PositiveIntegerField()),
            ],
        ),
    ]
